# -*- coding: utf-8 -*-
"""3operators_Alex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pk8BLw15SeMyf3eHXKrYa-UZdNyLe4rP
"""

#3operators.py

# 3.1 Operators

# 3.1.1 Multiply 4 with 8, and print the result.
# TODO: Write your code below
result = 4 * 8
print(result)



# 3.1.2 Divide 30 by 6, and print the result.
# TODO: Write your code below
result = 30 / 6
print(result)